export default [
    { id: "EVENT_ID", numeric: true, label: "ID Evento" },
    { id: "TYPE", numeric: false, label: "Tipo" },
    { id: "STATE", numeric: false, label: "Estado" },
    { id: "EVENTDATE", numeric: false, label: "Fecha Evento" },
    { id: "SOLVEDATE", numeric: false, label: "Fecha Solución" },
    { id: "ENDDATE", numeric: false, label: "Fecha Final" },
    { id: "ESCDATE", numeric: false, label: "Fecha Escalamiento" },
    { id: "SERVICE", numeric: false, label: "Servicio" },
    { id: "SYSTEM", numeric: false, label: "Sistema" },
    { id: "SUBSYS", numeric: false, label: "Subsistema" },
    { id: "TOTALP", numeric: true, label: "Total Pot." },
    { id: "PROBLEM", numeric: false, label: "Problema" },
    { id: "SEVERITY", numeric: true, label: "Criticidad" },
    { id: "ZONA", numeric: false, label: "Zona" },
    { id: "LOCALIDAD", numeric: false, label: "Localidad" },
    { id: "NODO", numeric: false, label: "Nodo" },
    { id: "CUADRANTE", numeric: false, label: "Cuadrante" },
    { id: "GEOREF", numeric: true, label: "Geo Ref." }
];
